# Generated by Django 5.2.10 on 2026-02-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_userreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hide_from_search',
            field=models.BooleanField(default=False, help_text='Hide your profile from browse/search results'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_verified',
            field=models.BooleanField(default=False, help_text='ID document verified by admin'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='incognito_mode',
            field=models.BooleanField(default=False, help_text='View other profiles without appearing in their visitors list'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(default=False, help_text='Phone number verified'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_online_status',
            field=models.BooleanField(default=True, help_text='Allow others to see when you are online'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='snapchat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='video_intro',
            field=models.FileField(blank=True, help_text='Short video introduction (optional)', null=True, upload_to='profile_videos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('members', 'Members Only - Visible to logged in users'), ('connections', 'Connections Only - Visible only to your matches')], default='members', help_text='Who can see your full profile', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Basic profile verification'),
        ),
    ]
