# Generated by Django 5.2.10 on 2026-02-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_userprofile_hide_from_search_userprofile_id_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='body_type',
            field=models.CharField(blank=True, choices=[('slim', 'Slim'), ('average', 'Average'), ('athletic', 'Athletic'), ('curvy', 'Curvy'), ('plus', 'Plus Size'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='drinks',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('occasionally', 'Occasionally'), ('yes', 'Yes')], max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='education_level',
            field=models.CharField(blank=True, choices=[('none', 'Prefer not to say'), ('secondary', 'High school / Secondary'), ('college', 'College / Diploma'), ('university', 'University Degree'), ('postgrad', 'Postgraduate')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('african', 'African'), ('afro_caribbean', 'Afro-Caribbean'), ('mixed', 'Mixed'), ('arab', 'Arab'), ('asian', 'Asian'), ('caucasian', 'Caucasian'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='relationship_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('dating', 'Dating'), ('married', 'Married'), ('complicated', "It's complicated")], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='smokes',
            field=models.CharField(blank=True, choices=[('no', 'No'), ('occasionally', 'Occasionally'), ('yes', 'Yes')], max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_kg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
