# Generated by Django 5.2.10 on 2026-02-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_userprofile_body_type_userprofile_drinks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='area',
            field=models.CharField(blank=True, choices=[('mirema', 'Mirema'), ('kasarani', 'Kasarani'), ('wandani', 'Wandani'), ('kimbo', 'Kimbo (Githurai Kimbo)'), ('roysambu', 'Roysambu'), ('zimmerman', 'Zimmerman'), ('githurai', 'Githurai'), ('thika_road_other', 'Other Thika Road Area'), ('nairobi_other', 'Other Nairobi Area'), ('other', 'Other')], help_text='Area/estate (e.g., Mirema, Kasarani, Kimbo)', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, help_text='City or town (e.g., Nairobi)', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, help_text='More detailed description, building or street (optional)', max_length=100),
        ),
    ]
