# Generated by Django 5.2.10 on 2026-02-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client - Looking for Escorts'), ('escort', 'Escort - Providing Services')], default='client', help_text='Are you looking for escorts or providing escort services?', max_length=10),
        ),
    ]
