# Generated by Django 5.2.10 on 2026-02-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='confirmation_code',
            field=models.CharField(blank=True, help_text='Payment confirmation code from user', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number used for payment', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text='Mobile money transaction reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payperviewpurchase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payperviewpurchase',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tip',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('mtn_mobile_money', 'MTN Mobile Money'), ('tigo_pesa', 'Tigo Pesa'), ('orange_money', 'Orange Money'), ('vodacom_mpesa', 'Vodacom M-Pesa'), ('mobile_money', 'Mobile Money (Generic)'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='mobile_money', max_length=30),
        ),
        migrations.AlterField(
            model_name='payperviewpurchase',
            name='payment_method',
            field=models.CharField(choices=[('tokens', 'Tokens'), ('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('mtn_mobile_money', 'MTN Mobile Money'), ('tigo_pesa', 'Tigo Pesa'), ('orange_money', 'Orange Money'), ('mobile_money', 'Mobile Money'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='mobile_money', max_length=30),
        ),
        migrations.AlterField(
            model_name='tip',
            name='payment_method',
            field=models.CharField(choices=[('tokens', 'Tokens'), ('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('mtn_mobile_money', 'MTN Mobile Money'), ('tigo_pesa', 'Tigo Pesa'), ('orange_money', 'Orange Money'), ('mobile_money', 'Mobile Money'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='mobile_money', max_length=30),
        ),
    ]
