# Generated by Django 5.2.10 on 2026-02-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_payment_confirmation_code_payment_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='earnings_tracking',
            field=models.BooleanField(default=False, help_text='Detailed earnings dashboard'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='featured_listing',
            field=models.BooleanField(default=False, help_text='Featured placement in search results'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='priority_ranking',
            field=models.BooleanField(default=False, help_text='Higher ranking in search results'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='profile_verification_badge',
            field=models.BooleanField(default=False, help_text='Verified escort badge'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='unlimited_photos',
            field=models.BooleanField(default=False, help_text='Unlimited profile photos'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client - For Users Looking for Escorts'), ('escort', 'Escort - For Escorts Providing Services'), ('both', 'Both - Available for Clients and Escorts')], default='client', help_text='Who is this plan for?', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='advanced_search',
            field=models.BooleanField(default=False, help_text='Advanced search filters'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='creator_earnings',
            field=models.BooleanField(default=False, help_text='Earn from content and tips'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('vip', 'VIP')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='unlimited_content_access',
            field=models.BooleanField(default=False, help_text='Access to all premium content'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='unlimited_messaging',
            field=models.BooleanField(default=False, help_text='Unlimited messages to escorts'),
        ),
    ]
