# Generated by Django 5.2.11 on 2026-02-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_plans_visible_to_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='billing_period',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('once', 'One Time')], default='monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('vip', 'VIP'), ('once', 'One Time Access')], max_length=20),
        ),
    ]
