# Generated by Django 5.2.11 on 2026-06-25 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscription_billing_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa STK Push'), ('mpesa_till', 'M-Pesa Till')], default='mobile_money', max_length=30),
        ),
    ]
