# Generated by Django 5.2.11 on 2026-02-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_subscription_billing_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('mtn_mobile_money', 'MTN Mobile Money'), ('tigo_pesa', 'Tigo Pesa'), ('orange_money', 'Orange Money'), ('vodacom_mpesa', 'Vodacom M-Pesa'), ('mobile_money', 'Mobile Money (Generic)'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='mobile_money', max_length=30),
        ),
        migrations.AlterField(
            model_name='payperviewpurchase',
            name='payment_method',
            field=models.CharField(choices=[('tokens', 'Tokens'), ('paystack', 'Paystack'), ('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('mtn_mobile_money', 'MTN Mobile Money'), ('tigo_pesa', 'Tigo Pesa'), ('orange_money', 'Orange Money'), ('mobile_money', 'Mobile Money'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='mobile_money', max_length=30),
        ),
        migrations.AlterField(
            model_name='tip',
            name='payment_method',
            field=models.CharField(choices=[('tokens', 'Tokens'), ('paystack', 'Paystack'), ('mpesa', 'M-Pesa'), ('airtel_money', 'Airtel Money'), ('mtn_mobile_money', 'MTN Mobile Money'), ('tigo_pesa', 'Tigo Pesa'), ('orange_money', 'Orange Money'), ('mobile_money', 'Mobile Money'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='mobile_money', max_length=30),
        ),
    ]
