# Generated by Django 5.2.11 on 2026-07-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_daily_weekly_premium_plans'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('tier', 'user_type')},
        ),
    ]
